#define _STLP_COMPILER "gcc"
#define _STLP_HAS_INCLUDE_NEXT 1
#define _STLP_CALL
#define _STLP_NORETURN_FUNCTION __attribute__((noreturn))
#define _STLP_LONG_LONG long long
#define _STLP_HAS_NATIVE_FLOAT_ABS
#define _STLP_NATIVE_INCLUDE_PATH NATIVE_INCLUDE_PATH
#define _STLP_HAS_NO_NEW_C_HEADERS
