// The following code is the modified part of the protobuf library
// available at http://code.google.com/p/protobuf/
// under the terms of the BSD 3-Clause License
// http://opensource.org/licenses/BSD-3-Clause

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/protobuf/compiler/plugin.proto

#ifndef PROTOBUF_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto__INCLUDED
#define PROTOBUF_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto__INCLUDED

#include <contrib/libs/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <contrib/libs/protobuf/generated_message_util.h>
#include <contrib/libs/protobuf/repeated_field.h>
#include <contrib/libs/protobuf/extension_set.h>
#include <contrib/libs/protobuf/generated_message_reflection.h>
#include "contrib/libs/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {
namespace compiler {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
void protobuf_AssignDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
void protobuf_ShutdownFile_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();

class CodeGeneratorRequest;
class CodeGeneratorResponse;
class CodeGeneratorResponse_File;

// ===================================================================

class CodeGeneratorRequest : public ::google::protobuf::Message {
 public:
  CodeGeneratorRequest();
  virtual ~CodeGeneratorRequest();
  
  CodeGeneratorRequest(const CodeGeneratorRequest& from);
  
  inline CodeGeneratorRequest& operator=(const CodeGeneratorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodeGeneratorRequest& default_instance();
  
  void Swap(CodeGeneratorRequest* other);
  
  // implements Message ----------------------------------------------
  
  CodeGeneratorRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CodeGeneratorRequest& from);
  void MergeFrom(const CodeGeneratorRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string file_to_generate = 1;
  inline int file_to_generate_size() const;
  inline void clear_file_to_generate();
  static const int kFileToGenerateFieldNumber = 1;
  inline const TProtoStringType& file_to_generate(int index) const;
  inline TProtoStringType* mutable_file_to_generate(int index);
  inline void set_file_to_generate(int index, const TProtoStringType& value);
  inline void set_file_to_generate(int index, const char* value);
  inline void set_file_to_generate(int index, const char* value, size_t size);
  inline TProtoStringType* add_file_to_generate();
  inline void add_file_to_generate(const TProtoStringType& value);
  inline void add_file_to_generate(const char* value);
  inline void add_file_to_generate(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< TProtoStringType>& file_to_generate() const;
  inline ::google::protobuf::RepeatedPtrField< TProtoStringType>* mutable_file_to_generate();
  
  // optional string parameter = 2;
  inline bool has_parameter() const;
  inline void clear_parameter();
  static const int kParameterFieldNumber = 2;
  inline const TProtoStringType& parameter() const;
  inline void set_parameter(const TProtoStringType& value);
  inline void set_parameter(const char* value);
  inline void set_parameter(const char* value, size_t size);
  inline TProtoStringType* mutable_parameter();
  
  // repeated .google.protobuf.FileDescriptorProto proto_file = 15;
  inline int proto_file_size() const;
  inline void clear_proto_file();
  static const int kProtoFileFieldNumber = 15;
  inline const ::google::protobuf::FileDescriptorProto& proto_file(int index) const;
  inline ::google::protobuf::FileDescriptorProto* mutable_proto_file(int index);
  inline ::google::protobuf::FileDescriptorProto* add_proto_file();
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >&
      proto_file() const;
  inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >*
      mutable_proto_file();
  
  // Yandex cpp-styleguide extension
  inline size_t file_to_generateSize() const { return (size_t)file_to_generate_size(); }
  inline void Clearfile_to_generate() { clear_file_to_generate(); }
  inline const TProtoStringType& Getfile_to_generate(int index) const { return file_to_generate(index); }
  inline TProtoStringType* Mutablefile_to_generate(int index) { return mutable_file_to_generate(index); }
  inline void Setfile_to_generate(int index, const TProtoStringType& value) { set_file_to_generate(index, value); }
  inline void Setfile_to_generate(int index, const char* value) { set_file_to_generate(index, value); }
  inline void Setfile_to_generate(int index, const char* value, size_t size) { set_file_to_generate(index, value, size); }
  inline TProtoStringType* Addfile_to_generate() { return add_file_to_generate(); }
  inline void Addfile_to_generate(const TProtoStringType& value) { add_file_to_generate(value); }
  inline void Addfile_to_generate(const char* value) { add_file_to_generate(value); }
  inline void Addfile_to_generate(const char* value, size_t size) { add_file_to_generate(value, size); }
  inline const TProtoStringType& get_idx_file_to_generate(int index) const { return file_to_generate(index); }
  inline const ::google::protobuf::RepeatedPtrField<TProtoStringType>& get_arr_file_to_generate() const{ return file_to_generate(); }
  inline const ::google::protobuf::RepeatedPtrField<TProtoStringType>& Getfile_to_generate() const{ return file_to_generate(); }
  inline ::google::protobuf::RepeatedPtrField<TProtoStringType>* Mutablefile_to_generate(){ return mutable_file_to_generate(); }
  
  inline bool Hasparameter() const { return has_parameter(); }
  inline void Clearparameter() { clear_parameter(); }
  inline const TProtoStringType& Getparameter() const { return parameter(); }
  inline void Setparameter(const TProtoStringType& value) { set_parameter(value); }
  inline void Setparameter(const char* value) { set_parameter(value); }
  inline void Setparameter(const char* value, size_t size) { set_parameter(value, size); }
  inline TProtoStringType* Mutableparameter() { return mutable_parameter(); }
  
  inline size_t proto_fileSize() const { return (size_t)proto_file_size(); }
  inline void Clearproto_file() { clear_proto_file(); }
  inline const ::google::protobuf::FileDescriptorProto& Getproto_file(int index) const { return proto_file(index); }
  inline ::google::protobuf::FileDescriptorProto* Mutableproto_file(int index) { return mutable_proto_file(index); }
  inline ::google::protobuf::FileDescriptorProto* Addproto_file() { return add_proto_file(); }
  inline const ::google::protobuf::FileDescriptorProto& get_idx_proto_file(int index) const { return proto_file(index); }
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >&
      get_arr_proto_file() const { return proto_file(); }
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >&
      Getproto_file() const { return proto_file(); }
  inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >*
      Mutableproto_file() { return mutable_proto_file(); }
  
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorRequest)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< TProtoStringType> file_to_generate_;
  TProtoStringType* parameter_;
  static const TProtoStringType _default_parameter_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto > proto_file_;
  friend void  protobuf_AddDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_AssignDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_ShutdownFile_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CodeGeneratorRequest* default_instance_;
};
// -------------------------------------------------------------------

class CodeGeneratorResponse_File : public ::google::protobuf::Message {
 public:
  CodeGeneratorResponse_File();
  virtual ~CodeGeneratorResponse_File();
  
  CodeGeneratorResponse_File(const CodeGeneratorResponse_File& from);
  
  inline CodeGeneratorResponse_File& operator=(const CodeGeneratorResponse_File& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodeGeneratorResponse_File& default_instance();
  
  void Swap(CodeGeneratorResponse_File* other);
  
  // implements Message ----------------------------------------------
  
  CodeGeneratorResponse_File* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CodeGeneratorResponse_File& from);
  void MergeFrom(const CodeGeneratorResponse_File& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const TProtoStringType& name() const;
  inline void set_name(const TProtoStringType& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline TProtoStringType* mutable_name();
  
  // optional string insertion_point = 2;
  inline bool has_insertion_point() const;
  inline void clear_insertion_point();
  static const int kInsertionPointFieldNumber = 2;
  inline const TProtoStringType& insertion_point() const;
  inline void set_insertion_point(const TProtoStringType& value);
  inline void set_insertion_point(const char* value);
  inline void set_insertion_point(const char* value, size_t size);
  inline TProtoStringType* mutable_insertion_point();
  
  // optional string content = 15;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 15;
  inline const TProtoStringType& content() const;
  inline void set_content(const TProtoStringType& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline TProtoStringType* mutable_content();
  
  // Yandex cpp-styleguide extension
  inline bool Hasname() const { return has_name(); }
  inline void Clearname() { clear_name(); }
  inline const TProtoStringType& Getname() const { return name(); }
  inline void Setname(const TProtoStringType& value) { set_name(value); }
  inline void Setname(const char* value) { set_name(value); }
  inline void Setname(const char* value, size_t size) { set_name(value, size); }
  inline TProtoStringType* Mutablename() { return mutable_name(); }
  
  inline bool Hasinsertion_point() const { return has_insertion_point(); }
  inline void Clearinsertion_point() { clear_insertion_point(); }
  inline const TProtoStringType& Getinsertion_point() const { return insertion_point(); }
  inline void Setinsertion_point(const TProtoStringType& value) { set_insertion_point(value); }
  inline void Setinsertion_point(const char* value) { set_insertion_point(value); }
  inline void Setinsertion_point(const char* value, size_t size) { set_insertion_point(value, size); }
  inline TProtoStringType* Mutableinsertion_point() { return mutable_insertion_point(); }
  
  inline bool Hascontent() const { return has_content(); }
  inline void Clearcontent() { clear_content(); }
  inline const TProtoStringType& Getcontent() const { return content(); }
  inline void Setcontent(const TProtoStringType& value) { set_content(value); }
  inline void Setcontent(const char* value) { set_content(value); }
  inline void Setcontent(const char* value, size_t size) { set_content(value, size); }
  inline TProtoStringType* Mutablecontent() { return mutable_content(); }
  
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorResponse.File)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  TProtoStringType* name_;
  static const TProtoStringType _default_name_;
  TProtoStringType* insertion_point_;
  static const TProtoStringType _default_insertion_point_;
  TProtoStringType* content_;
  static const TProtoStringType _default_content_;
  friend void  protobuf_AddDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_AssignDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_ShutdownFile_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CodeGeneratorResponse_File* default_instance_;
};
// -------------------------------------------------------------------

class CodeGeneratorResponse : public ::google::protobuf::Message {
 public:
  CodeGeneratorResponse();
  virtual ~CodeGeneratorResponse();
  
  CodeGeneratorResponse(const CodeGeneratorResponse& from);
  
  inline CodeGeneratorResponse& operator=(const CodeGeneratorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodeGeneratorResponse& default_instance();
  
  void Swap(CodeGeneratorResponse* other);
  
  // implements Message ----------------------------------------------
  
  CodeGeneratorResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CodeGeneratorResponse& from);
  void MergeFrom(const CodeGeneratorResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef CodeGeneratorResponse_File File;
  
  // accessors -------------------------------------------------------
  
  // optional string error = 1;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline const TProtoStringType& error() const;
  inline void set_error(const TProtoStringType& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline TProtoStringType* mutable_error();
  
  // repeated .google.protobuf.compiler.CodeGeneratorResponse.File file = 15;
  inline int file_size() const;
  inline void clear_file();
  static const int kFileFieldNumber = 15;
  inline const ::google::protobuf::compiler::CodeGeneratorResponse_File& file(int index) const;
  inline ::google::protobuf::compiler::CodeGeneratorResponse_File* mutable_file(int index);
  inline ::google::protobuf::compiler::CodeGeneratorResponse_File* add_file();
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >&
      file() const;
  inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >*
      mutable_file();
  
  // Yandex cpp-styleguide extension
  inline bool Haserror() const { return has_error(); }
  inline void Clearerror() { clear_error(); }
  inline const TProtoStringType& Geterror() const { return error(); }
  inline void Seterror(const TProtoStringType& value) { set_error(value); }
  inline void Seterror(const char* value) { set_error(value); }
  inline void Seterror(const char* value, size_t size) { set_error(value, size); }
  inline TProtoStringType* Mutableerror() { return mutable_error(); }
  
  inline size_t fileSize() const { return (size_t)file_size(); }
  inline void Clearfile() { clear_file(); }
  inline const ::google::protobuf::compiler::CodeGeneratorResponse_File& Getfile(int index) const { return file(index); }
  inline ::google::protobuf::compiler::CodeGeneratorResponse_File* Mutablefile(int index) { return mutable_file(index); }
  inline ::google::protobuf::compiler::CodeGeneratorResponse_File* Addfile() { return add_file(); }
  inline const ::google::protobuf::compiler::CodeGeneratorResponse_File& get_idx_file(int index) const { return file(index); }
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >&
      get_arr_file() const { return file(); }
  inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >&
      Getfile() const { return file(); }
  inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >*
      Mutablefile() { return mutable_file(); }
  
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorResponse)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  TProtoStringType* error_;
  static const TProtoStringType _default_error_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File > file_;
  friend void  protobuf_AddDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_AssignDesc_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  friend void protobuf_ShutdownFile_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CodeGeneratorResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// CodeGeneratorRequest

// repeated string file_to_generate = 1;
inline int CodeGeneratorRequest::file_to_generate_size() const {
  return file_to_generate_.size();
}
inline void CodeGeneratorRequest::clear_file_to_generate() {
  file_to_generate_.Clear();
}
inline const TProtoStringType& CodeGeneratorRequest::file_to_generate(int index) const {
  return file_to_generate_.Get(index);
}
inline TProtoStringType* CodeGeneratorRequest::mutable_file_to_generate(int index) {
  return file_to_generate_.Mutable(index);
}
inline void CodeGeneratorRequest::set_file_to_generate(int index, const TProtoStringType& value) {
  file_to_generate_.Mutable(index)->assign(value);
}
inline void CodeGeneratorRequest::set_file_to_generate(int index, const char* value) {
  file_to_generate_.Mutable(index)->assign(value);
}
inline void CodeGeneratorRequest::set_file_to_generate(int index, const char* value, size_t size) {
  file_to_generate_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorRequest::add_file_to_generate() {
  return file_to_generate_.Add();
}
inline void CodeGeneratorRequest::add_file_to_generate(const TProtoStringType& value) {
  file_to_generate_.Add()->assign(value);
}
inline void CodeGeneratorRequest::add_file_to_generate(const char* value) {
  file_to_generate_.Add()->assign(value);
}
inline void CodeGeneratorRequest::add_file_to_generate(const char* value, size_t size) {
  file_to_generate_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< TProtoStringType>&
CodeGeneratorRequest::file_to_generate() const {
  return file_to_generate_;
}
inline ::google::protobuf::RepeatedPtrField< TProtoStringType>*
CodeGeneratorRequest::mutable_file_to_generate() {
  return &file_to_generate_;
}

// optional string parameter = 2;
inline bool CodeGeneratorRequest::has_parameter() const {
  return _has_bit(1);
}
inline void CodeGeneratorRequest::clear_parameter() {
  if (parameter_ != &_default_parameter_) {
    parameter_->clear();
  }
  _clear_bit(1);
}
inline const TProtoStringType& CodeGeneratorRequest::parameter() const {
  return *parameter_;
}
inline void CodeGeneratorRequest::set_parameter(const TProtoStringType& value) {
  _set_bit(1);
  if (parameter_ == &_default_parameter_) {
    parameter_ = new TProtoStringType;
  }
  parameter_->assign(value);
}
inline void CodeGeneratorRequest::set_parameter(const char* value) {
  _set_bit(1);
  if (parameter_ == &_default_parameter_) {
    parameter_ = new TProtoStringType;
  }
  parameter_->assign(value);
}
inline void CodeGeneratorRequest::set_parameter(const char* value, size_t size) {
  _set_bit(1);
  if (parameter_ == &_default_parameter_) {
    parameter_ = new TProtoStringType;
  }
  parameter_->assign(reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorRequest::mutable_parameter() {
  _set_bit(1);
  if (parameter_ == &_default_parameter_) {
    parameter_ = new TProtoStringType;
  }
  return parameter_;
}

// repeated .google.protobuf.FileDescriptorProto proto_file = 15;
inline int CodeGeneratorRequest::proto_file_size() const {
  return proto_file_.size();
}
inline void CodeGeneratorRequest::clear_proto_file() {
  proto_file_.Clear();
}
inline const ::google::protobuf::FileDescriptorProto& CodeGeneratorRequest::proto_file(int index) const {
  return proto_file_.Get(index);
}
inline ::google::protobuf::FileDescriptorProto* CodeGeneratorRequest::mutable_proto_file(int index) {
  return proto_file_.Mutable(index);
}
inline ::google::protobuf::FileDescriptorProto* CodeGeneratorRequest::add_proto_file() {
  return proto_file_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >&
CodeGeneratorRequest::proto_file() const {
  return proto_file_;
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::FileDescriptorProto >*
CodeGeneratorRequest::mutable_proto_file() {
  return &proto_file_;
}

// -------------------------------------------------------------------

// CodeGeneratorResponse_File

// optional string name = 1;
inline bool CodeGeneratorResponse_File::has_name() const {
  return _has_bit(0);
}
inline void CodeGeneratorResponse_File::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(0);
}
inline const TProtoStringType& CodeGeneratorResponse_File::name() const {
  return *name_;
}
inline void CodeGeneratorResponse_File::set_name(const TProtoStringType& value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new TProtoStringType;
  }
  name_->assign(value);
}
inline void CodeGeneratorResponse_File::set_name(const char* value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new TProtoStringType;
  }
  name_->assign(value);
}
inline void CodeGeneratorResponse_File::set_name(const char* value, size_t size) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new TProtoStringType;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorResponse_File::mutable_name() {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new TProtoStringType;
  }
  return name_;
}

// optional string insertion_point = 2;
inline bool CodeGeneratorResponse_File::has_insertion_point() const {
  return _has_bit(1);
}
inline void CodeGeneratorResponse_File::clear_insertion_point() {
  if (insertion_point_ != &_default_insertion_point_) {
    insertion_point_->clear();
  }
  _clear_bit(1);
}
inline const TProtoStringType& CodeGeneratorResponse_File::insertion_point() const {
  return *insertion_point_;
}
inline void CodeGeneratorResponse_File::set_insertion_point(const TProtoStringType& value) {
  _set_bit(1);
  if (insertion_point_ == &_default_insertion_point_) {
    insertion_point_ = new TProtoStringType;
  }
  insertion_point_->assign(value);
}
inline void CodeGeneratorResponse_File::set_insertion_point(const char* value) {
  _set_bit(1);
  if (insertion_point_ == &_default_insertion_point_) {
    insertion_point_ = new TProtoStringType;
  }
  insertion_point_->assign(value);
}
inline void CodeGeneratorResponse_File::set_insertion_point(const char* value, size_t size) {
  _set_bit(1);
  if (insertion_point_ == &_default_insertion_point_) {
    insertion_point_ = new TProtoStringType;
  }
  insertion_point_->assign(reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorResponse_File::mutable_insertion_point() {
  _set_bit(1);
  if (insertion_point_ == &_default_insertion_point_) {
    insertion_point_ = new TProtoStringType;
  }
  return insertion_point_;
}

// optional string content = 15;
inline bool CodeGeneratorResponse_File::has_content() const {
  return _has_bit(2);
}
inline void CodeGeneratorResponse_File::clear_content() {
  if (content_ != &_default_content_) {
    content_->clear();
  }
  _clear_bit(2);
}
inline const TProtoStringType& CodeGeneratorResponse_File::content() const {
  return *content_;
}
inline void CodeGeneratorResponse_File::set_content(const TProtoStringType& value) {
  _set_bit(2);
  if (content_ == &_default_content_) {
    content_ = new TProtoStringType;
  }
  content_->assign(value);
}
inline void CodeGeneratorResponse_File::set_content(const char* value) {
  _set_bit(2);
  if (content_ == &_default_content_) {
    content_ = new TProtoStringType;
  }
  content_->assign(value);
}
inline void CodeGeneratorResponse_File::set_content(const char* value, size_t size) {
  _set_bit(2);
  if (content_ == &_default_content_) {
    content_ = new TProtoStringType;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorResponse_File::mutable_content() {
  _set_bit(2);
  if (content_ == &_default_content_) {
    content_ = new TProtoStringType;
  }
  return content_;
}

// -------------------------------------------------------------------

// CodeGeneratorResponse

// optional string error = 1;
inline bool CodeGeneratorResponse::has_error() const {
  return _has_bit(0);
}
inline void CodeGeneratorResponse::clear_error() {
  if (error_ != &_default_error_) {
    error_->clear();
  }
  _clear_bit(0);
}
inline const TProtoStringType& CodeGeneratorResponse::error() const {
  return *error_;
}
inline void CodeGeneratorResponse::set_error(const TProtoStringType& value) {
  _set_bit(0);
  if (error_ == &_default_error_) {
    error_ = new TProtoStringType;
  }
  error_->assign(value);
}
inline void CodeGeneratorResponse::set_error(const char* value) {
  _set_bit(0);
  if (error_ == &_default_error_) {
    error_ = new TProtoStringType;
  }
  error_->assign(value);
}
inline void CodeGeneratorResponse::set_error(const char* value, size_t size) {
  _set_bit(0);
  if (error_ == &_default_error_) {
    error_ = new TProtoStringType;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
}
inline TProtoStringType* CodeGeneratorResponse::mutable_error() {
  _set_bit(0);
  if (error_ == &_default_error_) {
    error_ = new TProtoStringType;
  }
  return error_;
}

// repeated .google.protobuf.compiler.CodeGeneratorResponse.File file = 15;
inline int CodeGeneratorResponse::file_size() const {
  return file_.size();
}
inline void CodeGeneratorResponse::clear_file() {
  file_.Clear();
}
inline const ::google::protobuf::compiler::CodeGeneratorResponse_File& CodeGeneratorResponse::file(int index) const {
  return file_.Get(index);
}
inline ::google::protobuf::compiler::CodeGeneratorResponse_File* CodeGeneratorResponse::mutable_file(int index) {
  return file_.Mutable(index);
}
inline ::google::protobuf::compiler::CodeGeneratorResponse_File* CodeGeneratorResponse::add_file() {
  return file_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >&
CodeGeneratorResponse::file() const {
  return file_;
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::compiler::CodeGeneratorResponse_File >*
CodeGeneratorResponse::mutable_file() {
  return &file_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace compiler
}  // namespace protobuf
}  // namespace google

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_contrib_2flibs_2fprotobuf_2fcompiler_2fplugin_2eproto__INCLUDED
